name: example
on: push
  #schedule:
  #  - cron: '*/5 * * * *' # Every 5 minutes
jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check Tickets
        uses: nightcoffee/melon-ticket-actions@master
        with:
          product-id: 210649
          schedule-id: 20250111
          seat-id: 1_0
          slack-incoming-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          message: '<@U4CF18RKL> 티켓사세요'
